[project]
name = "tao-te-ching"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "julia>=0.6.2",
    "memory-profiler>=0.61.0",
    "mmh3>=5.2.0",
    "numpy>=2.3.5",
    "pip>=25.3",
]
